import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { ItemLanguageGeneratedModule, ItemLanguageGeneratedSharedModule } from './generated/module';
import { ItemLanguageValidationRegistry, ItemLanguageValidator } from './item-language-validator';
import { ItemLangNameProvider } from './item-language-naming'
import { ItemLangScopeComputation, ItemLangScopeProvider } from './item-language-scope'

/**
 * Declaration of custom services - add your own service classes here.
 */
export type ItemLanguageAddedServices = {
    validation: {
        ItemLanguageValidator: ItemLanguageValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type ItemLanguageServices = LangiumServices & ItemLanguageAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const ItemLanguageModule: Module<ItemLanguageServices, PartialLangiumServices & ItemLanguageAddedServices> = {
    references: {
        ScopeComputation: (injector) => new ItemLangScopeComputation(injector),
        NameProvider: () => new ItemLangNameProvider(),
        ScopeProvider: (services) => new ItemLangScopeProvider(services)
    },
    validation: {
        ValidationRegistry: (services) => new ItemLanguageValidationRegistry(services),
        ItemLanguageValidator: () => new ItemLanguageValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createItemLanguageServices(context?: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    ItemLanguage: ItemLanguageServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        ItemLanguageGeneratedSharedModule
    );
    const ItemLanguage = inject(
        createDefaultModule({ shared }),
        ItemLanguageGeneratedModule,
        ItemLanguageModule
    );
    shared.ServiceRegistry.register(ItemLanguage);
    return { shared, ItemLanguage };
}
